#cloud-config
write_files:
  - content: |
      name: terraform-enterprise
      services:
        tfe:
          image: images.releases.hashicorp.com/hashicorp/terraform-enterprise:${tfe_version}
          environment:
            TFE_LICENSE_PATH: /opt/tfe-fdo/${license_filename}
            TFE_HOSTNAME: ${tfe_hostname}
            TFE_ENCRYPTION_PASSWORD: ${enc_password}
            TFE_OPERATIONAL_MODE: "external"
            TFE_DISK_CACHE_VOLUME_NAME: $${COMPOSE_PROJECT_NAME}_terraform-enterprise-cache
            TFE_TLS_CERT_FILE: /etc/ssl/private/terraform-enterprise/cert.pem
            TFE_TLS_KEY_FILE: /etc/ssl/private/terraform-enterprise/key.pem
            TFE_TLS_CA_BUNDLE_FILE: /etc/ssl/private/terraform-enterprise/bundle.pem

            # Database settings. See the configuration reference for more settings.
            TFE_DATABASE_USER: "${db_username}"
            TFE_DATABASE_PASSWORD: "${db_password}"
            TFE_DATABASE_HOST: "${db_host}"
            TFE_DATABASE_NAME: "${db_name}"
            TFE_DATABASE_PARAMETERS: "sslmode=disable"

            # Object storage settings. See the configuration reference for more settings.
            TFE_OBJECT_STORAGE_TYPE: "s3"
            TFE_OBJECT_STORAGE_S3_BUCKET: "${storage_bucket}"
            TFE_OBJECT_STORAGE_S3_REGION: "${aws_region}"
            TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: "true"

            # Redis settings. See the configuration reference for more settings.
            TFE_REDIS_HOST: "${redis_address}:${redis_port}"

            # Vault cluster settings.
            # If you are using the default internal vault, this should be the private routable IP address of the node itself.
            TFE_VAULT_CLUSTER_ADDRESS: "https://PRIVATE_IP_ADDRESS_WILL_BE_PLACED_HERE:8201"
          cap_add:
            - IPC_LOCK
          read_only: true
          tmpfs:
            - /tmp
            - /run
            - /var/log/terraform-enterprise
          ports:
            - "80:80"
            - "443:443"
            - "8201:8201"
          volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /run/docker.sock
            - type: bind
              source: ./certs
              target: /etc/ssl/private/terraform-enterprise
            - type: bind
              source: /opt/tfe-fdo
              target: /opt/tfe-fdo
            - type: volume
              source: terraform-enterprise-cache
              target: /var/cache/tfe-task-worker/terraform
      volumes:
        terraform-enterprise:
        terraform-enterprise-cache:
    permissions: '0640'
    path: /var/tmp/compose.yaml
  - content: |
       until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting to install Docker" ; sleep 3 ; done 

       #uninstall any older docker versions
       sudo apt-get remove -y docker.io docker-doc docker-compose podman-docker containerd runc

       #update the apt package
       sudo apt-get update
       sudo apt-get install ca-certificates curl gnupg

       #add docker official GPG key
       sudo install -m 0755 -d /etc/apt/keyrings
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
       sudo chmod a+r /etc/apt/keyrings/docker.gpg

       #setup the repository
       echo \
       "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
       "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
       sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

       #update the apt package index
       sudo apt-get update

       #install Docker Engine, containerd, and Docker Compose latest version
       sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    permissions: '0750'
    path: /var/tmp/install-docker.sh
  - content: |
       until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting to copy certs" ; sleep 3 ; done 

       #create a new directory dedicated to tfe and to add the certs
       mkdir -p /opt/tfe-fdo/certs

       #install awscli to get the certs from S3 bucket
       sudo apt-get -y install awscli

       #copy the certs from S3 locally, to my tfe-fdo/certs folder
       sudo aws s3 cp s3://${certs_bucket}/ssl-certs/full_chain /opt/tfe-fdo/certs/cert.pem
       sudo aws s3 cp s3://${certs_bucket}/ssl-certs/full_chain /opt/tfe-fdo/certs/bundle.pem
       sudo aws s3 cp s3://${certs_bucket}/ssl-certs/private_key_pem /opt/tfe-fdo/certs/key.pem

       #copy the TFE FDO license to the tfe-fdo/ folder
       sudo aws s3 cp s3://${license_bucket}/${license_filename} /opt/tfe-fdo/${license_filename}

       #retrieve the private ip of the EC2 instance and save it to a variable
       AWS_TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` 
       LOCAL_IP=`curl -H "X-aws-ec2-metadata-token: $AWS_TOKEN" -v http://169.254.169.254/latest/meta-data/local-ipv4`
       sed -i "s/PRIVATE_IP_ADDRESS_WILL_BE_PLACED_HERE/$LOCAL_IP/g" /var/tmp/compose.yaml


       #login to the Terraform Enterprise container image registry
       cat /opt/tfe-fdo/${license_filename} | sudo docker login --username terraform images.releases.hashicorp.com --password-stdin

       #pull the TFE image from the registry
       docker pull images.releases.hashicorp.com/hashicorp/terraform-enterprise:${tfe_version}

       #copy compose file
       cp /var/tmp/compose.yaml /opt/tfe-fdo
 
       #spin up TFE
       pushd /opt/tfe-fdo
       #mkdir -p /root/tfe-fdo
       docker compose up --detach
    permissions: '0750'
    path: /var/tmp/install-tfe.sh
  - content: |
      {
        "username": "${username}",
        "email": "${email}",
        "password": "${password}"
      }
    permissions: '0750'
    path: /opt/tfe-fdo/payload-iact.json
  - content: |
      #!/bin/bash
      #We have to wait for TFE be fully functioning before we can continue
      while true; do
          if curl -kI "https://${tfe_hostname}/admin" 2>&1 | grep -w "200\|301" ;
          then
              echo "TFE is up and running"
              echo "Will continue in 1 minutes with the final steps"
              sleep 60
              break
          else
              echo "TFE is not available yet. Please wait..."
              sleep 60
          fi
      done

      #go to the tfe folder
      pushd /opt/tfe-fdo

      #get iact token
      IACT_TOKEN=`docker compose exec tfe retrieve-iact | tee /opt/tfe-fdo/iact-token.txt`

      #create the first admin user
      curl -k \
          --header "Content-Type: application/json" \
          --request POST \
          --data @/opt/tfe-fdo/payload-iact.json \
          https://${tfe_hostname}/admin/initial-admin-user?token=$IACT_TOKEN | tee /opt/tfe-fdo/initial-admin-user.json
    permissions: '0750'
    path: /var/tmp/create-admin-user.sh   
runcmd:
  - until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for final steps" ; sleep 3 ; done 
  - sudo bash /var/tmp/install-docker.sh
  - sudo bash /var/tmp/install-tfe.sh
  - sudo bash /var/tmp/create-admin-user.sh
packages_update: true
packages:
  - unzip
